using KoeNote.App.Models;
using KoeNote.App.Services.Export;

namespace KoeNote.App.ViewModels;

public sealed partial class MainWindowViewModel
{
    private void InitializeCommands()
    {
        AddAudioCommand = new RelayCommand(AddAudioAsync);
        DeleteJobCommand = new RelayCommand<JobSummary>(DeleteJobAsync, job => job is not null && !IsRunInProgress);
        ClearAllJobsCommand = new RelayCommand(ClearAllJobsAsync, () => Jobs.Count > 0 && !IsRunInProgress);
        ClearJobSearchCommand = new RelayCommand(ClearJobSearchAsync, () => !string.IsNullOrEmpty(JobSearchText));
        ClearSegmentSearchCommand = new RelayCommand(ClearSegmentSearchAsync, () => !string.IsNullOrEmpty(SegmentSearchText));
        RestoreJobCommand = new RelayCommand<JobSummary>(RestoreJobAsync, job => job is not null && !IsRunInProgress);
        PermanentlyDeleteJobCommand = new RelayCommand<JobSummary>(PermanentlyDeleteJobAsync, job => job is not null && !IsRunInProgress);
        PermanentlyDeleteAllDeletedJobsCommand = new RelayCommand(PermanentlyDeleteAllDeletedJobsAsync, () => DeletedJobs.Count > 0 && !IsRunInProgress);
        RunSelectedJobCommand = new RelayCommand(RunSelectedJobAsync, () => CanRunSelectedJob);
        RunPostReviewCommand = new RelayCommand(() => RequestPostProcessAsync(PostProcessMode.ReviewOnly), () => CanRunPostReview);
        RunPostSummaryCommand = new RelayCommand(() => RequestPostProcessAsync(PostProcessMode.SummaryOnly), () => CanRunPostSummary);
        RunReadablePolishingCommand = new RelayCommand(RunReadablePolishingAsync, () => CanRunReadablePolishing);
        CopyReadablePolishedContentCommand = new RelayCommand(CopyReadablePolishedContentAsync, () => HasReadablePolishedContent);
        ShowReadableTranscriptTabCommand = new RelayCommand(() => SelectTranscriptTabAsync(ReadableTranscriptTabIndex));
        ShowRawTranscriptTabCommand = new RelayCommand(() => SelectTranscriptTabAsync(RawTranscriptTabIndex));
        ShowDiffTranscriptTabCommand = new RelayCommand(() => SelectTranscriptTabAsync(DiffTranscriptTabIndex));
        ShowReviewCandidateTranscriptTabCommand = new RelayCommand(() => SelectTranscriptTabAsync(ReviewCandidateTranscriptTabIndex));
        // Compatibility command for non-header callers; the normal UX separates review and summary.
        RunPostReviewAndSummaryCommand = new RelayCommand(() => RequestPostProcessAsync(PostProcessMode.ReviewAndSummary), () => CanRunPostReviewAndSummary);
        CancelCommand = new RelayCommand(CancelRunAsync, () => IsRunInProgress);
        PlayPauseAudioCommand = new RelayCommand(PlayPauseAudioAsync, CanPlaySelectedJobAudio);
        SkipToPreviousSegmentCommand = new RelayCommand(SkipToPreviousSegmentAsync, CanSkipPlaybackSegment);
        SkipToNextSegmentCommand = new RelayCommand(SkipToNextSegmentAsync, CanSkipPlaybackSegment);
        OpenSettingsCommand = new RelayCommand(OpenSettingsAsync);
        OpenLogsCommand = new RelayCommand(OpenLogsAsync);
        ExportLogsCommand = new RelayCommand(ExportLogsAsync, CanExportLogs);
        OpenLogFolderCommand = new RelayCommand(OpenLogFolderAsync);
        OpenCleanupToolCommand = new RelayCommand(OpenCleanupToolAsync, CanOpenCleanupTool);
        ImportDomainPresetCommand = new RelayCommand(ImportDomainPresetAsync, () => !IsRunInProgress);
        ApplyLoadedDomainPresetCommand = new RelayCommand(ApplyLoadedDomainPresetAsync, () => !IsRunInProgress && HasLoadedDomainPreset);
        ClearDomainPresetCommand = new RelayCommand(ClearSelectedDomainPresetAsync, () => SelectedDomainPresetImport?.DeactivatedAt is null && !IsRunInProgress);
        OpenSetupCommand = new RelayCommand(OpenSetupAsync);
        CloseSetupWizardModalCommand = new RelayCommand(CloseSetupWizardModalAsync, CanCloseSetupWizardModal);
        OpenSelectedDetailPanelCommand = new RelayCommand(OpenSelectedDetailPanelAsync, CanOpenSelectedDetailPanel);
        CloseDetailPanelCommand = new RelayCommand(CloseDetailPanelAsync);
        SetupBackCommand = new RelayCommand(SetupBackAsync, CanUseSetupBackAction);
        SetupNextCommand = new RelayCommand(SetupNextAsync, CanUseSetupNextAction);
        SetupUseRecommendedCommand = new RelayCommand(SetupUseRecommendedAsync);
        SetupAcceptLicensesCommand = new RelayCommand(SetupAcceptLicensesAsync);
        SetupInstallSelectedPresetCommand = new RelayCommand(SetupInstallSelectedPresetAsync, CanInstallSelectedPreset);
        SetupCancelInstallCommand = new RelayCommand(SetupCancelInstallAsync, CanCancelSetupInstall);
        SetupDownloadAsrCommand = new RelayCommand(SetupDownloadAsrAsync, CanDownloadSetupAsr);
        SetupDownloadReviewCommand = new RelayCommand(SetupDownloadReviewAsync, CanDownloadSetupReview);
        SetupInstallDiarizationRuntimeCommand = new RelayCommand(SetupInstallDiarizationRuntimeAsync, CanInstallDiarizationRuntime);
        SetupInstallAsrCudaRuntimeCommand = new RelayCommand(SetupInstallAsrCudaRuntimeAsync, CanInstallAsrCudaRuntime);
        SetupInstallCudaReviewRuntimeCommand = new RelayCommand(SetupInstallCudaReviewRuntimeAsync, CanInstallCudaReviewRuntime);
        SetupRegisterLocalAsrCommand = new RelayCommand(SetupRegisterLocalAsrAsync, CanUseSetupInstallActions);
        SetupRegisterLocalReviewCommand = new RelayCommand(SetupRegisterLocalReviewAsync, CanUseSetupInstallActions);
        SetupImportOfflinePackCommand = new RelayCommand(SetupImportOfflinePackAsync, CanUseSetupInstallActions);
        SetupChooseStorageRootCommand = new RelayCommand(SetupChooseStorageRootAsync);
        SetupRunSmokeCommand = new RelayCommand(SetupRunSmokeAsync);
        SetupCompleteCommand = new RelayCommand(SetupCompleteAsync);
        ShowModelCatalogCommand = new RelayCommand(ShowModelCatalogAsync);
        RegisterPreinstalledModelsCommand = new RelayCommand(RegisterPreinstalledModelsAsync);
        DownloadSelectedModelCommand = new RelayCommand(DownloadSelectedModelAsync, CanDownloadSelectedModel);
        PauseSelectedModelDownloadCommand = new RelayCommand(PauseSelectedModelDownloadAsync, CanPauseSelectedModelDownload);
        ResumeSelectedModelDownloadCommand = new RelayCommand(ResumeSelectedModelDownloadAsync, CanResumeSelectedModelDownload);
        CancelSelectedModelDownloadCommand = new RelayCommand(CancelSelectedModelDownloadAsync, CanCancelSelectedModelDownload);
        RetrySelectedModelDownloadCommand = new RelayCommand(RetrySelectedModelDownloadAsync, CanRetrySelectedModelDownload);
        UseSelectedModelCommand = new RelayCommand(UseSelectedModelAsync, () => SelectedModelCatalogEntry is not null);
        ShowSelectedModelLicenseCommand = new RelayCommand(ShowSelectedModelLicenseAsync, () => SelectedModelCatalogEntry is not null);
        DeleteSelectedModelFilesCommand = new RelayCommand(DeleteSelectedModelFilesAsync, CanDeleteSelectedModelFiles);
        AcceptDraftCommand = new RelayCommand(AcceptSelectedDraftAsync, CanOperateOnSelectedDraft);
        RejectDraftCommand = new RelayCommand(RejectSelectedDraftAsync, CanOperateOnSelectedDraft);
        ApplyManualEditCommand = new RelayCommand(ApplyManualEditAsync, CanOperateOnSelectedDraft);
        SelectPreviousDraftCommand = new RelayCommand(SelectPreviousDraftAsync, CanSelectPreviousDraft);
        SelectNextDraftCommand = new RelayCommand(SelectNextDraftAsync, CanSelectNextDraft);
        FocusSelectedDraftSegmentCommand = new RelayCommand(FocusSelectedDraftSegmentAsync, () => SelectedCorrectionDraft is not null);
        SaveSegmentEditCommand = new RelayCommand(SaveSegmentEditAsync, CanEditSelectedSegment);
        BeginSegmentInlineEditCommand = new RelayCommand<TranscriptSegmentPreview>(BeginSegmentInlineEditAsync, CanBeginSegmentInlineEdit);
        SaveSegmentInlineEditCommand = new RelayCommand(SaveSegmentInlineEditAsync, CanEditSelectedSegment);
        CancelSegmentInlineEditCommand = new RelayCommand(CancelSegmentInlineEditAsync, () => IsSegmentInlineEditActive);
        RevertSegmentEditCommand = new RelayCommand<TranscriptSegmentPreview>(RevertSegmentEditAsync, CanRevertSegmentEdit);
        BeginSpeakerInlineEditCommand = new RelayCommand<TranscriptSegmentPreview>(BeginSpeakerInlineEditAsync, CanBeginSpeakerInlineEdit);
        SaveSpeakerInlineEditCommand = new RelayCommand(SaveSpeakerInlineEditAsync, CanEditSelectedSpeaker);
        SaveSpeakerAliasCommand = new RelayCommand(SaveSpeakerAliasAsync, CanEditSelectedSpeaker);
        UndoLastOperationCommand = new RelayCommand(UndoLastOperationAsync);
        ExportSelectedJobCommand = new RelayCommand(ExportSelectedJobAsync, CanExportReadablePolishing);
        ExportTxtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Text), CanExportReadablePolishing);
        ExportJsonCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Json, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportSrtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Srt, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportDocxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Docx), CanExportReadablePolishing);
        ExportRawTxtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Text, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawMarkdownCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Markdown, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawXlsxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Xlsx, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawJsonCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Json, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawSrtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Srt, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawVttCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Vtt, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportRawDocxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Docx, TranscriptExportSource.Raw), CanExportSelectedJob);
        ExportPolishedTxtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Text, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportPolishedMarkdownCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Markdown, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportPolishedXlsxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Xlsx, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportPolishedDocxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Docx, TranscriptExportSource.Polished), CanExportSelectedJob);
        ExportReadablePolishedTxtCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Text, TranscriptExportSource.ReadablePolished), CanExportReadablePolishing);
        ExportReadablePolishedMarkdownCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Markdown, TranscriptExportSource.ReadablePolished), CanExportReadablePolishing);
        ExportReadablePolishedXlsxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Xlsx, TranscriptExportSource.ReadablePolished), CanExportReadablePolishing);
        ExportReadablePolishedDocxCommand = new RelayCommand(() => ExportSelectedJobFormatAsync(TranscriptExportFormat.Docx, TranscriptExportSource.ReadablePolished), CanExportReadablePolishing);
        ExportSummaryMarkdownCommand = new RelayCommand(ExportSummaryMarkdownAsync, CanExportSummaryMarkdown);
        ExportSummaryTextCommand = new RelayCommand(ExportSummaryTextAsync, CanExportSummaryMarkdown);
        OpenExportFolderCommand = new RelayCommand(OpenExportFolderAsync, CanOpenExportFolder);
        ZoomOutCommand = new RelayCommand(ZoomOutAsync, CanZoomOut);
        ZoomInCommand = new RelayCommand(ZoomInAsync, CanZoomIn);
        ResetZoomCommand = new RelayCommand(ResetZoomAsync, () => _mainContentZoomState.CanReset);
        RunDatabaseMaintenanceCommand = new RelayCommand(RunDatabaseMaintenanceAsync, CanRunDatabaseMaintenance);
        CheckForUpdatesCommand = new RelayCommand(CheckForUpdatesAsync, () => !IsUpdateCheckInProgress);
        DownloadUpdateCommand = new RelayCommand(DownloadUpdateAsync, CanDownloadUpdate);
        InstallVerifiedUpdateCommand = new RelayCommand(InstallVerifiedUpdateAsync, CanInstallVerifiedUpdate);
        DismissUpdateNotificationCommand = new RelayCommand(DismissUpdateNotificationAsync);
        OpenUpdateReleaseNotesCommand = new RelayCommand(OpenUpdateReleaseNotesAsync, () => AvailableUpdateReleaseNotesUrl is not null);
        SaveReadablePolishingPromptSettingsCommand = new RelayCommand(SaveReadablePolishingPromptSettings);
        ResetReadablePolishingPromptSettingsCommand = new RelayCommand(ResetReadablePolishingPromptSettings);
        SelectActiveReadablePolishingPromptModelFamilyCommand = new RelayCommand(SelectActiveReadablePolishingPromptModelFamily);
    }
}
